'use client';

import { useEffect, useState } from 'react';
// import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/features/landing/nav/Navbar';
import ClientTestimonials from '@/features/landing/testimonials/ClientTestimonials';
import FreeAuditForm from '@/features/landing/freeAuditForm/FreeAuditForm';
import FAQsSection from '@/features/landing/FAQsSection/FAQsSection';
import Footer from '@/features/landing/footer/footer';
import { fetchHomepage } from '@/lib/api';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Techorphic',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isNavbarVisible, setIsNavbarVisible] = useState(false);
  const [footerData, setFooterData] = useState<any>(null);
  const [faqData, setFaqData] = useState<any[]>([]);
  const [faqTitle, setFaqTitle] = useState<string>('FAQS');

  useEffect(() => {
    const handleScroll = () => {
      const scrollY = window.scrollY;
      const viewportHeight = window.innerHeight;

      // Show navbar when scrolled past 100vh
      setIsNavbarVisible(scrollY > viewportHeight);
    };

    window.addEventListener('scroll', handleScroll);

    // ✅ fetch homepage and set footer + faq
    fetchHomepage().then((data) => {
      if (data?.Footer?.length) {
        setFooterData(data.Footer[0]);
      }
      if (data?.FAQSection?.length) {
        const faqSection = data.FAQSection[0];
        setFaqData(faqSection.faqitem || []);
        setFaqTitle(faqSection.title || 'FAQS');
      }
    });

    // Cleanup
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          className={`fixed w-full flex items-center justify-end  z-50 transition-transform duration-300 ease-in-out ${
            isNavbarVisible ? 'translate-y-0' : '-translate-y-full'
          }`}
          style={{ top: 0 }}
        >
          <button className="mx-3 py-3 text-white">Menu</button>
        </div>

        {children}
        <ClientTestimonials />
        <FreeAuditForm />
        {/* ✅ Pass FAQ data safely */}
        <FAQsSection faqs={faqData} title={faqTitle} />
        {/* ✅ Pass footer data safely */}
        <Footer footer={footerData} />
      </body>
    </html>
  );
}
