'use client';

import { useEffect, useState } from 'react';
// import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/features/landing/nav/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Techorphic',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isNavbarVisible, setIsNavbarVisible] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      const scrollY = window.scrollY;
      const viewportHeight = window.innerHeight;

      // Show navbar when scrolled past 100vh
      setIsNavbarVisible(scrollY > viewportHeight);
    };

    window.addEventListener('scroll', handleScroll);

    // Cleanup
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div
          className={`fixed w-full flex items-center justify-end  z-50 transition-transform duration-300 ease-in-out ${
            isNavbarVisible ? 'translate-y-0' : '-translate-y-full'
          }`}
          style={{ top: 0 }}
        >
          <button className="mx-3 py-3 text-white">Menu</button>
        </div>

        {children}
      </body>
    </html>
  );
}
